export function loadConfig(env = process.env) {
  return {
    port: Number(env.PORT || 4318),
    host: env.HOST || "0.0.0.0",
    dataFile: env.DATA_FILE || "data/db.json",
    publicBaseUrl: trimSlash(env.PUBLIC_BASE_URL || `http://localhost:${env.PORT || 4318}`),
    autoMode: env.AUTO_MODE || "limited",
    autoPublishThreshold: Number(env.AUTO_PUBLISH_THRESHOLD || 85),
    reviewThreshold: Number(env.REVIEW_THRESHOLD || 70),
    scrapeIntervalMinutes: Number(env.SCRAPE_INTERVAL_MINUTES || 60),
    publishIntervalMinutes: Number(env.PUBLISH_INTERVAL_MINUTES || 10),
    scraperMode: env.SCRAPER_MODE || "mock",
    scraperFallbackMock: env.SCRAPER_FALLBACK_MOCK !== "false",
    amazonSearchUrls: parseList(env.AMAZON_SEARCH_URLS || [
      "https://www.amazon.com.br/s?k=logitech&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=hyperx&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=razer&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=jbl&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=anker+soundcore&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=sony+fone&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=kingston+ssd&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=samsung+ssd&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=lg+ultragear&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=tp+link+deco&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=notebook+dell&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=notebook+lenovo&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=notebook+acer&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=notebook+asus&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=monitor+lg&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=monitor+samsung&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=monitor+aoc&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=smart+tv+samsung&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=smart+tv+lg&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=smart+tv+tcl&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=smart+tv+philips&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=soundbar+samsung&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=soundbar+lg&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=cadeira+flexform&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=cadeira+gamer+husky&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=mesa+gamer&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=mesa+escrivaninha&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=apple+airpods&deals-promo-filter=1",
      "https://www.amazon.com.br/s?k=echo+show&deals-promo-filter=1"
    ].join(",")),
    disclosure: env.AFFILIATE_DISCLOSURE || "Link de afiliado: posso receber comissao pela compra.",
    amazonAffiliateTag: env.AMAZON_AFFILIATE_TAG || "",
    amazonAffiliateTagTelegram: env.AMAZON_AFFILIATE_TAG_TELEGRAM || "",
    amazonAffiliateTagX: env.AMAZON_AFFILIATE_TAG_X || "",
    amazonAffiliateTagAdmin: env.AMAZON_AFFILIATE_TAG_ADMIN || "",
    amazonCreatorUrl: env.AMAZON_CREATOR_URL || "",
    mercadoLivreAffiliateParam: env.MERCADO_LIVRE_AFFILIATE_PARAM || "",
    telegramBotToken: env.TELEGRAM_BOT_TOKEN || "",
    telegramChatId: env.TELEGRAM_CHAT_ID || "",
    telegramDryRun: env.TELEGRAM_DRY_RUN !== "false",
    xDryRun: env.X_DRY_RUN !== "false",
    xProfileUrl: env.X_PROFILE_URL || "",
    xApiKey: env.X_API_KEY || "",
    xApiSecret: env.X_API_SECRET || "",
    xAccessToken: env.X_ACCESS_TOKEN || "",
    xAccessSecret: env.X_ACCESS_SECRET || "",
    discordWebhookUrl: env.DISCORD_WEBHOOK_URL || "",
    discordDryRun: env.DISCORD_DRY_RUN !== "false",
    adminToken: env.ADMIN_TOKEN || "",
    openaiApiKey: env.OPENAI_API_KEY || "",
    anthropicApiKey: env.ANTHROPIC_API_KEY || "",
    aiConfidenceThreshold: Number(env.AI_CONFIDENCE_THRESHOLD || 70),
    telegramChannelUrl: env.TELEGRAM_CHANNEL_URL || "",
    discordInviteUrl: env.DISCORD_INVITE_URL || "",
    rssEnabled: env.RSS_ENABLED !== "false",
    maxPublicationsPerCycle: Number(env.MAX_PUBLICATIONS_PER_CYCLE || 4),
    publicationWindowHours: Number(env.PUBLICATION_WINDOW_HOURS || 1),
    minPublicationIntervalMinutes: Number(env.MIN_PUBLICATION_INTERVAL_MINUTES || 15),
    premiumBrands: env.PREMIUM_BRANDS || "",
    secondaryBrands: env.SECONDARY_BRANDS || "",
    premiumCurationMinScore: Number(env.PREMIUM_CURATION_MIN_SCORE || 30),
    maxPremiumCategoryPerWindow: Number(env.MAX_PREMIUM_CATEGORY_PER_WINDOW || 1),
    allowExternalProductImages: env.ALLOW_EXTERNAL_PRODUCT_IMAGES === "true",
    maxCandidatesPerCycle: Number(env.MAX_CANDIDATES_PER_CYCLE || 2),
    databaseUrl: env.DATABASE_URL || "",
    redisUrl: env.REDIS_URL || "",
    braveSearchApiKey: env.BRAVE_SEARCH_API_KEY || "",
    serpApiKey: env.SERP_API_KEY || ""
  };
}

function trimSlash(value) {
  return value.replace(/\/+$/, "");
}

function parseList(value) {
  return String(value)
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}
